disabled_rules:
  - cyclomatic_complexity 
  - file_length
  - function_body_length
  - function_parameter_count
  - opening_brace
  - nesting
  - type_body_length
  - variable_name
  - comma
  - colon
excluded:
  - Carthage
  - Pods
colon:
  flexible_right_spacing: true
line_length: 250
